### ISSUE TITLE
Max retries exceeded with url: /jsonrpc (Caused by None)

### ISSUE THREAD

**Issue by Rui-Zhou-2** [StanfordVL/taskonomy#62]
Hello, when I try to download the dataset by `omnitools.download all --components taskonomy --subset tiny  --dest ./taskonomy_dataset/  --connections_total 40 --agree --name --email` 

it will give me this error, what should I do?

`Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=6800): Max retries exceeded with url: /jsonrpc (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x110b5e5b0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/multiprocess/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.9/site-packages/omnidata_tools/dataset/download.py", line 298, in process_model
    raise e
  File "/usr/local/lib/python3.9/site-packages/omnidata_tools/dataset/download.py", line 283, in process_model
    tar_fpath = download_tar(
  File "/usr/local/lib/python3.9/site-packages/omnidata_tools/dataset/download.py", line 160, in download_tar
    res = aria2api.client.add_uri(uris=[url], options=options_dict)
  File "/usr/local/lib/python3.9/site-packages/aria2p/client.py", line 482, in add_uri
    return self.call(self.ADD_URI, params=[uris, options, position])  # type: ignore
  File "/usr/local/lib/python3.9/site-packages/aria2p/client.py", line 262, in call
    return self.res_or_raise(self.post(payload))
  File "/usr/local/lib/python3.9/site-packages/aria2p/client.py", line 358, in post
    return requests.post(self.server, data=payload, timeout=self.timeout).json()
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=6800): Max retries exceeded with url: /jsonrpc (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x110b5e5b0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/omnitools.download", line 8, in <module>
    sys.exit(download())
  File "/usr/local/lib/python3.9/site-packages/fastcore/script.py", line 113, in _f
    tfunc(**merge(args, args_from_prog(func, xtra)))
  File "/usr/local/lib/python3.9/site-packages/omnidata_tools/dataset/download.py", line 304, in download
    errors = list(tqdm.tqdm(p.imap(process_model, models), total=len(models)))
  File "/usr/local/lib/python3.9/site-packages/tqdm/std.py", line 1180, in __iter__
    for obj in iterable:
  File "/usr/local/lib/python3.9/site-packages/multiprocess/pool.py", line 870, in next
    raise value
requests.exceptions.ConnectionError: None: Max retries exceeded with url: /jsonrpc (Caused by None)

07/01 16:16:31 [NOTICE] Shutdown sequence commencing... Press Ctrl-C again for emergency shutdown.

Download Results:
gid   |stat|avg speed  |path/URI`

With great thanks

**Comment by kalyani7195** [comment]
I am getting the same error!
