### ISSUE TITLE
Network is unreachable

### ISSUE THREAD

**Issue by xRay2016** [StanfordVL/taskonomy#68]
Hi!

I am trying to download the dataset. But I encountered the following errors even when I download the `tiny` subset. I am in China, so I don't know if it is my own problem, and I want to  know how to solve it.

```
Traceback (most recent call last):
  File "/home/xdl/miniconda3/lib/python3.8/urllib/request.py", line 1350, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/home/xdl/miniconda3/lib/python3.8/http/client.py", line 1240, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/xdl/miniconda3/lib/python3.8/http/client.py", line 1286, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/xdl/miniconda3/lib/python3.8/http/client.py", line 1235, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/xdl/miniconda3/lib/python3.8/http/client.py", line 1006, in _send_output
    self.send(msg)
  File "/home/xdl/miniconda3/lib/python3.8/http/client.py", line 946, in send
    self.connect()
  File "/home/xdl/miniconda3/lib/python3.8/http/client.py", line 1402, in connect
    super().connect()
  File "/home/xdl/miniconda3/lib/python3.8/http/client.py", line 917, in connect
    self.sock = self._create_connection(
  File "/home/xdl/miniconda3/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/home/xdl/miniconda3/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable
```

**Comment by alexsax** [comment]
Hi @xRay2016,

You could try the old way of using `wget` or `curl` to download the files (though you are on your own for un-tarring them--it's not too bad). This is basically what the `aria` tool is supposed to do, but some people have had trouble with it. 

Each building + modality corresponds to a tar tile in the following. For example: `wiconisco_depth_euclidean.tar.tz`
```
https://datasets.epfl.ch/omnidata/links.txt
https://datasets.epfl.ch/taskonomy/links.txt
```
What I'd recommend is `wget`ing the taskonomy file, filter the modalities you want using `grep`, and then downloading + untarring them in parallel.

**Comment by xRay2016** [comment]
Thanks! The problem has been solved. Thanks!

**Comment by zzzyzh** [comment]
Hi, I'm from China too. 
I encountered the same problem as you when I tried to download tiny and would like to ask how I should use the .txt provided by the author to download only the tiny dataset? Is there a quick way to do this, thanks for your reply!
