### ISSUE TITLE
Unable to download the dataset.

### ISSUE THREAD

**Issue by Jiaqi-Chen-00** [StanfordVL/taskonomy#73]
Hello, thank you for your wonderful research and generous open-source contribution. May I ask which tutorial should I refer to for downloading the dataset and whether registration is required? I followed the link in your repository (https://github.com/StanfordVL/taskonomy/tree/master/data) to download the dataset, and used the following command: 

> sudo apt-get install aria2
pip install omnidata-tools
omnitools.download all --components taskonomy --subset fullplus \
  --dest ./taskonomy_dataset/ \
  --connections_total 40 --agree

**Error is following:**
> [LICENSE] Before continuing the download, please review the terms of use for each of the following component datasets:
[LICENSE]     omnidata: https://raw.githubusercontent.com/EPFL-VILAB/omnidata-tools/main/LICENSE
[LICENSE]     taskonomy: https://raw.githubusercontent.com/StanfordVL/taskonomy/master/data/LICENSE
Traceback (most recent call last):
  File "/home/chenjiaqi/anaconda3/envs/mmseg/bin/omnitools.download", line 8, in <module>
    sys.exit(download())
  File "/home/chenjiaqi/anaconda3/envs/mmseg/lib/python3.8/site-packages/fastcore/script.py", line 119, in _f
    return tfunc(**merge(args, args_from_prog(func, xtra)))
  File "/home/chenjiaqi/anaconda3/envs/mmseg/lib/python3.8/site-packages/omnidata_tools/dataset/download.py", line 260, in download
    licenses_clickthrough(components, require_prompt=not agree_all, component_to_license=component_to_license, email=email, name=name)
  File "/home/chenjiaqi/anaconda3/envs/mmseg/lib/python3.8/site-packages/omnidata_tools/dataset/download.py", line 76, in licenses_clickthrough
    if not (name and email_valid(email)): raise ValueError("In order to use --agree_all you must also supply a name and valid email through the args --name NAME and --email USER@DOMAIN)")
ValueError: In order to use --agree_all you must also supply a name and valid email through the args --name NAME and --email USER@DOMAIN)

Thank you!

**Comment by RikkiXu** [comment]
I have the same problem, may I know if you solved it?

**Comment by bookuil** [comment]
you should enter your name and your email through the args. 
which may look like this: 
omnitools.download all --components taskonomy --subset fullplus
--dest ./taskonomy_dataset/
--connections_total 40 --agree
--name  [your name]
--email [your email]

**Comment by kpup1710** [comment]
> you should enter your name and your email through the args. which may look like this: omnitools.download all --components taskonomy --subset fullplus --dest ./taskonomy_dataset/ --connections_total 40 --agree --name [your name] --email [your email]

I have tried this but got this error:
```
[FAILURE] Uncaught error when processing model https://datasets.epfl.ch/omnidata/omnidata_tars/point_info/replica/point_info-replica-frl_apartment_0.tar (stacktrace below)
[FAILURE] Uncaught error when processing model https://datasets.epfl.ch/omnidata/omnidata_tars/rgb/replica/rgb-replica-frl_apartment_0.tar (stacktrace below)
[FAILURE] Uncaught error when processing model https://datasets.epfl.ch/taskonomy/allensville_rgb.tar (stacktrace below)
[FAILURE] Uncaught error when processing model https://datasets.epfl.ch/taskonomy/allensville_point_info.tar (stacktrace below)
Exception in thread Thread-3 (_handle_results):
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/root/miniconda3/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/root/miniconda3/lib/python3.11/site-packages/multiprocess/pool.py", line 579, in _handle_results
    task = get()
           ^^^^^
  File "/root/miniconda3/lib/python3.11/site-packages/multiprocess/connection.py", line 253, in recv
    return _ForkingPickler.loads(buf.getbuffer())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.11/site-packages/dill/_dill.py", line 301, in loads
    return load(file, ignore, **kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.11/site-packages/dill/_dill.py", line 287, in load
    return Unpickler(file, ignore=ignore, **kwds).load()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.11/site-packages/dill/_dill.py", line 442, in load
    obj = StockUnpickler.load(self)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.11/site-packages/requests/exceptions.py", line 41, in __init__
    CompatJSONDecodeError.__init__(self, *args)
TypeError: JSONDecodeError.__init__() missing 2 required positional arguments: 'doc' and 'pos'
  ```

**Comment by wangxiaobobuyanqi** [comment]
hello, did you download the dataset from windows or linux?
