### ISSUE TITLE
Unable to download dataset

### ISSUE THREAD

**Issue by hafizuriu** [StanfordVL/taskonomy#74]
I'm facing problem to download the dataset. 
I used the following command:

`sudo apt-get install aria2` 
`pip install omnidata-tools`
`omnitools.download all --components taskonomy --subset fullplus
--dest ./taskonomy_dataset/
--connections_total 40 --agree
`

**Error is following:**

```
/home/hafizur/anaconda3/lib/python3.9/site-packages/fastcore/docscrape.py:225: UserWarning: potentially wrong underline length... 
Downloads Omnidata starter dataset. 
--- in 
Downloads Omnidata starter dataset.
---...
  else: warn(msg)
[HEADER] -------------------------------------
[HEADER] From SERVERS: (using checksum validation: False)
[HEADER]     https://datasets.epfl.ch/omnidata//links.txt
[HEADER]     https://datasets.epfl.ch/taskonomy//links.txt
[HEADER] 
[HEADER] Data parameters: (what to download)
[HEADER]     Domains    = ['all']
[HEADER]     Components = ['taskonomy']
[HEADER]     Subset     = fullplus
[HEADER]     Split      = all
[HEADER] 
[HEADER] Data locations:
[HEADER]     Dataset (extracted)      = ./taskonomy_dataset/
[HEADER]     Compressed files         = compressed/
[HEADER] -------------------------------------


[LICENSE] Before continuing the download, please review the terms of use for each of the following component datasets:
[LICENSE]     taskonomy: https://raw.githubusercontent.com/StanfordVL/taskonomy/master/data/LICENSE
[LICENSE]     omnidata: https://raw.githubusercontent.com/EPFL-VILAB/omnidata-tools/main/LICENSE
Traceback (most recent call last):
  File "/home/hafizur/anaconda3/bin/omnitools.download", line 8, in <module>
    sys.exit(download())
  File "/home/hafizur/anaconda3/lib/python3.9/site-packages/fastcore/script.py", line 119, in _f
    return tfunc(**merge(args, args_from_prog(func, xtra)))
  File "/home/hafizur/anaconda3/lib/python3.9/site-packages/omnidata_tools/dataset/download.py", line 260, in download
    licenses_clickthrough(components, require_prompt=not agree_all, component_to_license=component_to_license, email=email, name=name)
  File "/home/hafizur/anaconda3/lib/python3.9/site-packages/omnidata_tools/dataset/download.py", line 76, in licenses_clickthrough
    if not (name and email_valid(email)): raise ValueError("In order to use --agree_all you must also supply a name and valid email through the args --name NAME and --email USER@DOMAIN)")
ValueError: In order to use --agree_all you must also supply a name and valid email through the args --name NAME and --email USER@DOMAIN) 
```

**Comment by ijihoon98** [comment]
Enter --name NAME and --email USER@DOMAIN as parameters.

**Comment by hafizuriu** [comment]
Thank you so much. Now it works.

**Comment by hafizuriu** [comment]
How can I download a portion of taskonomy dataset instead of download the full dataset?

**Comment by bookuil** [comment]
just change the subset parameter

**Comment by wangxiaobobuyanqi** [comment]
hello, did you download the dataset from windows or linux?

**Comment by hafizuriu** [comment]
> hello, did you download the dataset from windows or linux?

I downloaded it from my linux machine.

**Comment by MengqingSun** [comment]
Hello, may I ask which version of the Taskonomy dataset you have downloaded? Is it the tiny version or the full version?
