### ISSUE TITLE
Error while downloading the dataset

### ISSUE THREAD

**Issue by kpup1710** [StanfordVL/taskonomy#77]
I have entered --name and --email parameters but still got this issue. Below is the terminal log.

Downloads Omnidata starter dataset. 
--- in 
Downloads Omnidata starter dataset.
---...
  else: warn(msg)
[HEADER] -------------------------------------
[HEADER] From SERVERS: (using checksum validation: False)
[HEADER]     https://datasets.epfl.ch/omnidata//links.txt
[HEADER]     https://datasets.epfl.ch/taskonomy//links.txt
[HEADER] 
[HEADER] Data parameters: (what to download)
[HEADER]     Domains    = ['rgb', 'normals', 'point_info']
[HEADER]     Components = ['replica', 'taskonomy']
[HEADER]     Subset     = debug
[HEADER]     Split      = all
[HEADER] 
[HEADER] Data locations:
[HEADER]     Dataset (extracted)      = ./omnidata_starter_dataset/
[HEADER]     Compressed files         = compressed/
[HEADER] -------------------------------------

[LICENSE] Before continuing the download, please review the terms of use for each of the following component datasets:
[LICENSE]     taskonomy: https://raw.githubusercontent.com/StanfordVL/taskonomy/master/data/LICENSE
[LICENSE]     replica: https://raw.githubusercontent.com/facebookresearch/Replica-Dataset/main/LICENSE
[LICENSE]     omnidata: https://raw.githubusercontent.com/EPFL-VILAB/omnidata-tools/main/LICENSE
dung nguyenvietd67@gmail.com
[NOTICE] Confirmation supplied by option '--agree_all'

[NOTICE] Opening aria2c download daemon in background: Run 'aria2p' in another window to view status.

11/14 07:40:35 [WARN] Neither --rpc-secret nor a combination of --rpc-user and --rpc-passwd is set. This is insecure. It is extremely recommended to specify --rpc-secret with the adequate secrecy or now deprecated --rpc-user and --rpc-passwd.

11/14 07:40:35 [NOTICE] IPv4 RPC: listening on TCP port 6800
['rgb', 'normals', 'point_info']                                                                                                                                                     
[NOTICE] Filtered down to 4 models based on specified criteria.
[NOTICE] Found 4 matching blobs on remote serverss.
  0%|                                                                                                                                                           | 0/4 [00:00<?, ?it/s][FAILURE] Uncaught error when processing model https://datasets.epfl.ch/omnidata/omnidata_tars/point_info/replica/point_info-replica-frl_apartment_0.tar (stacktrace below)
[FAILURE] Uncaught error when processing model https://datasets.epfl.ch/omnidata/omnidata_tars/rgb/replica/rgb-replica-frl_apartment_0.tar (stacktrace below)
[FAILURE] Uncaught error when processing model https://datasets.epfl.ch/taskonomy/allensville_rgb.tar (stacktrace below)
[FAILURE] Uncaught error when processing model https://datasets.epfl.ch/taskonomy/allensville_point_info.tar (stacktrace below)
Exception in thread Thread-3 (_handle_results):
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/root/miniconda3/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/root/miniconda3/lib/python3.11/site-packages/multiprocess/pool.py", line 579, in _handle_results
    task = get()
           ^^^^^
  File "/root/miniconda3/lib/python3.11/site-packages/multiprocess/connection.py", line 253, in recv
    return _ForkingPickler.loads(buf.getbuffer())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.11/site-packages/dill/_dill.py", line 301, in loads
    return load(file, ignore, **kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.11/site-packages/dill/_dill.py", line 287, in load
    return Unpickler(file, ignore=ignore, **kwds).load()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.11/site-packages/dill/_dill.py", line 442, in load
    obj = StockUnpickler.load(self)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.11/site-packages/requests/exceptions.py", line 41, in __init__
    CompatJSONDecodeError.__init__(self, *args)
TypeError: JSONDecodeError.__init__() missing 2 required positional arguments: 'doc' and 'pos'

**Comment by wangxiaobobuyanqi** [comment]
hello, did you download the dataset from windows or linux?
